#!/usr/bin/expect
set timeout 10
set passwd [lindex $argv 0]
spawn passwd admin
expect "Enter new UNIX password:"
send "$passwd\r"
expect "Retype new UNIX password:"
send "$passwd\r"
expect eof
exit

