#!/usr/bin/env python
import mq
import log
import sys
import time
import json
import zmq

def main():
    if len(sys.argv) >= 2:
        pub = mq.pub_socket('notification')
        pub.send_json({})
        time.sleep(0.5)
        pub.send_json({'message':str(sys.argv[1])})

if __name__ == '__main__':
    main()
