#!/usr/bin/env python
import log
import sys

def main():
    if len(sys.argv) == 2:
        level = 'info'
        msg = sys.argv[1]
    else:
        level = sys.argv[1]
        msg = sys.argv[2]

    journal = getattr(log, 'journal_%s'%level.lower(), log.journal_info)
    journal(msg)

if __name__ == '__main__':
    main()
